log:
  lever: info
  filePath: /home/logs

server:
  port: 8080

spring: 
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
      username: root
      password: root
      initial-size: 1
      max-active: 20
      max-wait: 600000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      min-evictable-idle-time-millis: 300000
      filters: stat
      stat-view-servlet:
        loginUsername: druid
        loginPassword: druid
        url-pattern: /druid/*

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000 # 连接超时时间 单位 ms（毫秒）
    pool:
      max-idle: 5 # 连接池中的最大空闲连接，默认值也是8
      min-idle: 1 #连接池中的最小空闲连接，默认值也是0
      max-active: 10 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
      max-wait: 3000 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      
      
security:
  basic:
    enabled: true
    path: /admin/* ,/management   #针对/management路径进行认证
  user:
    name: admin     #认证使用的用户名
    password: admin   #认证使用的密码
management:
  port: 8070 #指定管理端口和IP
  address: 127.0.0.1 #指定管理IP
  context-path: /management
  security:
    roles: SUPERUSER
